[package]
name = "aerodrome-substreams"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.6.0"
substreams-ethereum = "0.10.6"
hex = "0.4"
anyhow = "1.0"